config/routes.rb
Rails.application.routes.draw do
 

  resources :to_do_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
  root 'to_do_lists#index'

end

app/models/to_do_list.rb
class ToDoList < ActiveRecord::Base
	validates :title, presence: true 
	validates :title, length: { minimum: 3 }
	validates :description, presence: true 
	validates :description, length: { minimum: 5 }
	has_many :todo_items
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :to_do_list
  validates :content, presence: true, 
  					length: { minimum: 3 }
  def completed?
  	!complited_at.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/to_do_lists_controller.rb
class ToDoListsController < ApplicationController
  before_action :set_to_do_list, only: [:show, :edit, :update, :destroy]

  def index
    @to_do_lists = ToDoList.all
  end

  def show
  end

  def new
    @to_do_list = ToDoList.new
  end


  def edit
  end

  def create
    @to_do_list = ToDoList.new(to_do_list_params)

    respond_to do |format|
      if @to_do_list.save
        format.html { redirect_to @to_do_list, notice: 'To do list was successfully created.' }
        format.json { render :show, status: :created, location: @to_do_list }
      else
        format.html { render :new }
        format.json { render json: @to_do_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @to_do_list.update(to_do_list_params)
        format.html { redirect_to @to_do_list, notice: 'To do list was successfully updated.' }
        format.json { render :show, status: :ok, location: @to_do_list }
      else
        format.html { render :edit }
        format.json { render json: @to_do_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @to_do_list.destroy
    respond_to do |format|
      format.html { redirect_to to_do_lists_url, notice: 'To do list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_to_do_list
      @to_do_list = ToDoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def to_do_list_params
      params.require(:to_do_list).permit(:title, :description)
    end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :find_to_do_list  

  def index
  end

  def new
   	@todo_item = @todo_list.todo_items.new
  end

  def create

  	@todo_item = @todo_list.todo_items.new(todo_item_params)
  	if @todo_item.save
  		flash[:success] = "Added new item to the list!"
  		redirect_to to_do_list_todo_items_path
  	else
  		flash[:error] = "There are some problems with additing item."
  		render action: :new
  	end
  end

  def edit 

    @todo_item = @todo_list.todo_items.find(params[:id])
  end

  def update 
    
    @todo_item = @todo_list.todo_items.find(params[:id])
    if @todo_item.update_attributes(todo_item_params)
      flash[:success] = "Saved item to the list!"
      redirect_to to_do_list_todo_items_path
    else
      flash[:error] = "There are some problems with saving item."
      render action: :edit
    end
  end

  def url_options
    { to_do_list_id: params[:to_do_list_id] }.merge(super)
  end

  def destroy
    @todo_item = @todo_list.todo_items.find(params[:id])
    if @todo_item.destroy
      flash[:success] = "Todo list item was deleted!"
    else
      flash[:error] = "Todo item couldn't be deleted from this list." 
    end
    redirect_to to_do_list_todo_items_path
  end

  def complete
    @todo_item = @todo_list.todo_items.find(params[:id])
    @todo_item.update_attribute(:complited_at, Time.now)
    redirect_to to_do_list_todo_items_path, notice: "Todo item marked as complited."
  end

  private
    def find_to_do_list
      @todo_list = ToDoList.find(params[:to_do_list_id])
    end


  	def todo_item_params
  		params[:todo_item].permit(:content)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/to_do_lists_helper.rb
module ToDoListsHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="nav">
	<h1> <%= link_to "Home", root_path %> </h1>
	<ul>
		<li> <%= link_to "Todo Lists", to_do_lists_path %> </li>
	</ul>
	<br class="clear" />
</div>

<% flash.each do |type, message| %>
	<div class="alert flash <%= type %>" >
		<%= message %>
	</div>
<% end %>

<%= yield %>

</body>
</html>

app/views/to_do_lists/_form.html.erb
<%= form_for(@to_do_list) do |f| %>
  <% if @to_do_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@to_do_list.errors.count, "error") %> prohibited this to_do_list from being saved:</h2>

      <ul>
      <% @to_do_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/to_do_lists/edit.html.erb
<h1>Editing to_do_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @to_do_list %> |
<%= link_to 'Back', to_do_lists_path %>

app/views/to_do_lists/index.html.erb
<h1>Todo Lists</h1>

<% @to_do_lists.each do |to_do_list| %>
  <div class="todo_list" id="<%= dom_id(to_do_list) %>">
    <h2><%= to_do_list.title %></h2>
    <p><%= to_do_list.description %></p>
    <ul class="functions">
      <li><%= link_to 'List Items', to_do_list_todo_items_path(to_do_list) %> </li>
      <li><%= link_to 'Show', to_do_list %> </li>
      <li><%= link_to 'Edit', edit_to_do_list_path(to_do_list) %> </li>
      <li><%= link_to 'Destroy', to_do_list, method: :delete, data: { confirm: 'Are you sure?' } %> </li>
    </ul>
  </div>
  <br class="clear">
<% end %>

<br>
<%= link_to 'New To do list', new_to_do_list_path %>

app/views/to_do_lists/new.html.erb
<h1>New to_do_list</h1>

<%= render 'form' %>

<%= link_to 'Back', to_do_lists_path %>

app/views/to_do_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @to_do_list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @to_do_list.description %>
</p>

<%= link_to 'Edit', edit_to_do_list_path(@to_do_list) %> |
<%= link_to 'Back', to_do_lists_path %>

app/views/todo_items/_form.html.erb
<%= form_for [@todo_list, @todo_item] do |f| %>
	<div id="error_explanation">
	  <% unless @todo_item.errors.empty? %>
	  	<h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this to_do_list from being saved:</h2>
	  <% end %>

	  <ul>
	  <% @todo_item.errors.full_messages.each do |message| %>
	    <li><%= message %></li>
	  <% end %>
	  </ul>
	</div>

	<%= f.label :content %>
	<%= f.text_field :content %>
	<%= f.submit "Save" %>
<% end %>

app/views/todo_items/edit.html.erb
<h1><%= @todo_list.title %>  - Editing to list item : </h1>
<%= render partial: "form" %>

app/views/todo_items/index.html.erb
<h1 class="list_title"><%= @todo_list.title %> </h1>

<table class="todo_list">
	<thead>
		<tr> 
			<th width="25%"> Complited? </th> 
			<th width="60%"> Items </th> 
			<th width="15%"> Options </th> 
		</tr>
	</thead>

	<tbody>
	<% @todo_list.todo_items.each do |todo_item|%>
		<tr id="<%= dom_id(todo_item) %>"> 
			<% if todo_item.completed? %>
				<td> <%= todo_item.complited_at%> </td>
			<% else %>
				<td>  <%= link_to "Mark Complete", complete_to_do_list_todo_item_path(todo_item), method: :patch%> </td>
			<% end %>
			<td> <%= todo_item.content %> </td>
			<td> <%= link_to "Edit", edit_to_do_list_todo_item_path(todo_item) %> </td>
			<td> <%= link_to "Delete", to_do_list_todo_item_path(todo_item), method: :delete, data: { confirm: "Are you sure??"} %> </td>
			
		</tr>	
	<% end %>
</tbody>
</table>

<p>
	<%= link_to "New Todo Item", new_to_do_list_todo_item_path%>
</p>

app/views/todo_items/new.html.erb
<%= render partial: "form" %>